title: Queensland Education Developer Portal
logo_img: /assets/img/icons/IdentityImage.png
favicon: /assets/favicon.ico
description: A portal to support internal and external developers in the creation and management of applications for use in Queensland's Education community.
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © Department of Education 2022
# theme: jekyll-theme-simplex
remote_theme: andreondra/jekyll-theme-simplex

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"